updated some files

diff --git a/k8s/pre-sync.yaml b/k8s/pre-sync.yaml
--- a/k8s/pre-sync.yaml
+++ b/k8s/pre-sync.yaml
@@ -1,25 +1,25 @@
-apiVersion: batch/v1
-kind: Job
-metadata:
-  name: presync-health-check
-  annotations:
-    argocd.argoproj.io/hook: PreSync
-    argocd.argoproj.io/hook-delete-policy: HookSucceeded
-spec:
-  backoffLimit: 0   # <--- No retries on failure
-  template:
-    spec:
-      containers:
-      - name: vault-check
-        image: curlimages/curl:latest
-        command: 
-        - /bin/sh
-        - -c
-        - echo "thi is pre sync runs successfully"
-          # if [ "$(curl -s -o /dev/null -w "%{http_code}" https://vault-ui.vault.svc.cluster.local/v1/sys/health)" -ne 200 ]; then
-          #   echo "Vault is not running properly. Exiting..."
-          #   exit 1
-          # else
-          #   echo "Vault is up and running."
-          # fi
-      restartPolicy: Never
+# apiVersion: batch/v1
+# kind: Job
+# metadata:
+#   name: presync-health-check
+#   annotations:
+#     argocd.argoproj.io/hook: PreSync
+#     argocd.argoproj.io/hook-delete-policy: HookSucceeded
+# spec:
+#   backoffLimit: 0   # <--- No retries on failure
+#   template:
+#     spec:
+#       containers:
+#       - name: vault-check
+#         image: curlimages/curl:latest
+#         command: 
+#         - /bin/sh
+#         - -c
+#         - echo "thi is pre sync runs successfully"
+#           # if [ "$(curl -s -o /dev/null -w "%{http_code}" https://vault-ui.vault.svc.cluster.local/v1/sys/health)" -ne 200 ]; then
+#           #   echo "Vault is not running properly. Exiting..."
+#           #   exit 1
+#           # else
+#           #   echo "Vault is up and running."
+#           # fi
+#       restartPolicy: Never
